apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://d81f76a7-7ee9-4637-8411-c989b729b99d.k8s.ondigitalocean.com
  name: do-sgp1-k8s-1-25-4-do-0-sgp1-1677055136001
- cluster:
    certificate-authority: /Users/yuehernkang/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Mon, 12 Jun 2023 10:53:37 +08
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://127.0.0.1:53181
  name: minikube
contexts:
- context:
    cluster: do-sgp1-k8s-1-25-4-do-0-sgp1-1677055136001
    user: do-sgp1-k8s-1-25-4-do-0-sgp1-1677055136001-admin
  name: do-sgp1-k8s-1-25-4-do-0-sgp1-1677055136001
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 12 Jun 2023 10:53:37 +08
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: do-sgp1-k8s-1-25-4-do-0-sgp1-1677055136001-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=default
      - d81f76a7-7ee9-4637-8411-c989b729b99d
      command: doctl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: minikube
  user:
    client-certificate: /Users/yuehernkang/.minikube/profiles/minikube/client.crt
    client-key: /Users/yuehernkang/.minikube/profiles/minikube/client.key
